<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>

    <!-- Gör koden renare (slipper System; osv) -->
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- Hjälper oss fånga null-problem tidigt -->
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
